version: '3'

services:
  andnetwork9discord:
    container_name: AndNetwork9.Discord
    image: ${DOCKER_REGISTRY-}andnetwork9discord
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/Discord/Dockerfile
    depends_on: 
      - database
      - broker

  andnetwork9server:
    container_name: AndNetwork9.Server
    image: ${DOCKER_REGISTRY-}andnetwork9server
    restart: "no"
    env_file: .env
    ports:
      - "5260:80"
    build:
      context: .
      dockerfile: AndNetwork9/Server/Dockerfile
    depends_on: 
      - database
      - broker

  andnetwork9storage:
    container_name: AndNetwork9.Storage
    image: ${DOCKER_REGISTRY-}andnetwork9storage
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/Storage/Dockerfile
    depends_on: 
      - database
      - broker
    volumes:
      - "./data/repos:/var/lib/AndNetwork9/data"

  andnetwork9elections:
    container_name: AndNetwork9.Elections
    image: ${DOCKER_REGISTRY-}andnetwork9elections
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/Elections/Dockerfile
    depends_on: 
      - database
      - broker

  andnetwork9steam:
    container_name: AndNetwork9.Steam
    image: ${DOCKER_REGISTRY-}andnetwork9steam
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/Steam/Dockerfile
    depends_on: 
      - broker

  andnetwork9vk:
    container_name: AndNetwork9.VK
    image: ${DOCKER_REGISTRY-}andnetwork9vk
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/VK/Dockerfile
    depends_on: 
      - broker

  andnetwork9awarddispenser:
    container_name: AndNetwork9.AwardDispenser
    image: ${DOCKER_REGISTRY-}awarddispenser
    restart: "no"
    env_file: .env
    build:
      context: .
      dockerfile: AndNetwork9/AwardDispenser/Dockerfile
    depends_on: 
      - broker
      - database

  database:
    container_name: AndNetwork9.Database
    image: postgres:alpine
    restart: "no"
    env_file: .env
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"

#  redis:
#    container_name: AndNetwork9.Redis
#    image: redis:alpine
#    restart: "no"
#    volumes:
#      - "./data/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  broker:
    container_name: AndNetwork9.Broker
    image: rabbitmq:alpine
    restart: "no"
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - "./data/rabbitmq/rabbitmq.conf:/var/lib/rabbitmq/rabbitmq.conf"