// <auto-generated />
using And9.Client.Clan.Config.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace And9.Client.Clan.Config.Migrations
{
    [DbContext(typeof(ApplicationDataService))]
    [Migration("20220131192303_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("System.Tuple<int>", b =>
                {
                    b.Property<int>("Item1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Item1");

                    b.ToTable("GaveAwards");
                });

            modelBuilder.Entity("System.Tuple<string, string>", b =>
                {
                    b.Property<string>("Item1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Item1");

                    b.ToTable("ConfigValues");

                    b.HasData(
                        new
                        {
                            Item1 = "CLAN_DOMAIN",
                            Item2 = "5.19.254.243:5240"
                        },
                        new
                        {
                            Item1 = "LOGIN",
                            Item2 = ""
                        },
                        new
                        {
                            Item1 = "PASSWORD",
                            Item2 = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
