// <auto-generated />
using System;
using System.Collections.Generic;
using And9.Service.Auth.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace And9.Service.Auth.Database.Migrations
{
    [DbContext(typeof(AuthDataContext))]
    [Migration("20220103174829_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Auth")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("And9.Service.Auth.Database.Models.AccessRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<int>>("AllowedMembersIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<short[]>("Directions")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<DateTime>("LastChanged")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("MinRank")
                        .HasColumnType("smallint");

                    b.Property<short?>("SquadNumber")
                        .HasColumnType("smallint");

                    b.Property<short?>("SquadPartNumber")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("AccessRules", "Auth");
                });

            modelBuilder.Entity("And9.Service.Auth.Database.Models.PasswordHash", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("PasswordHashes", "Auth");
                });
#pragma warning restore 612, 618
        }
    }
}
