namespace And9.Service.Core.Abstractions.Enums;

public enum Rank : sbyte
{
    Outcast = sbyte.MinValue,
    Enemy = -7,
    Guest = -6,
    Diplomat = -5,
    Ally = -4,
    Auxiliary = -3,
    SeniorAuxiliary = -2,
    Candidate = -1,
    None = 0,
    Neophyte,
    Trainee,
    Assistant,
    JuniorEmployee,
    Employee,
    SeniorEmployee,
    JuniorSpecialist,
    Specialist,
    SeniorSpecialist,
    JuniorIntercessor,
    Intercessor,
    SeniorIntercessor,
    JuniorSentinel,
    Sentinel,
    SeniorSentinel,
    Advisor,
    FirstAdvisor = sbyte.MaxValue,
}