//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace And9.Service.Core.Abstractions.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("And9.Service.Core.Abstractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле «Discord» должно быть заполнено.
        /// </summary>
        public static string CandidateRequest_Discord_Required {
            get {
                return ResourceManager.GetString("CandidateRequest.Discord.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля «Количество часов» не может быть отрицательным.
        /// </summary>
        public static string CandidateRequest_HoursCount_Range {
            get {
                return ResourceManager.GetString("CandidateRequest.HoursCount.Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля «Никнейм» не может быть более 24 символов.
        /// </summary>
        public static string CandidateRequest_Nickname_MaxLength {
            get {
                return ResourceManager.GetString("CandidateRequest.Nickname.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никнейм не может быть пустым.
        /// </summary>
        public static string CandidateRequest_Nickname_MinLength {
            get {
                return ResourceManager.GetString("CandidateRequest.Nickname.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле «Никнейм» должно быть заполнено.
        /// </summary>
        public static string CandidateRequest_Nickname_Required {
            get {
                return ResourceManager.GetString("CandidateRequest.Nickname.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле «Steam» должно быть заполнено.
        /// </summary>
        public static string CandidateRequest_Steam_Required {
            get {
                return ResourceManager.GetString("CandidateRequest.Steam.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агитация и внешние связи.
        /// </summary>
        public static string Direction_Agitation {
            get {
                return ResourceManager.GetString("Direction.Agitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ауксилия.
        /// </summary>
        public static string Direction_Auxiliary {
            get {
                return ResourceManager.GetString("Direction.Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развитие и инфраструктура.
        /// </summary>
        public static string Direction_Infrastructure {
            get {
                return ResourceManager.GetString("Direction.Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атака и оборона.
        /// </summary>
        public static string Direction_Military {
            get {
                return ResourceManager.GetString("Direction.Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        public static string Direction_None {
            get {
                return ResourceManager.GetString("Direction.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исследования и разработка.
        /// </summary>
        public static string Direction_Research {
            get {
                return ResourceManager.GetString("Direction.Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резерв.
        /// </summary>
        public static string Direction_Reserve {
            get {
                return ResourceManager.GetString("Direction.Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обучение и тренировка.
        /// </summary>
        public static string Direction_Training {
            get {
                return ResourceManager.GetString("Direction.Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Советник.
        /// </summary>
        public static string Rank_Advisor {
            get {
                return ResourceManager.GetString("Rank.Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на △.
        /// </summary>
        public static string Rank_Advisor_Icon {
            get {
                return ResourceManager.GetString("Rank.Advisor.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Союзник.
        /// </summary>
        public static string Rank_Ally {
            get {
                return ResourceManager.GetString("Rank.Ally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ассистент.
        /// </summary>
        public static string Rank_Assistant {
            get {
                return ResourceManager.GetString("Rank.Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⦁.
        /// </summary>
        public static string Rank_Assistant_Icon {
            get {
                return ResourceManager.GetString("Rank.Assistant.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ауксилий.
        /// </summary>
        public static string Rank_Auxiliary {
            get {
                return ResourceManager.GetString("Rank.Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⭡⭡⭡.
        /// </summary>
        public static string Rank_Auxiliary_Icon {
            get {
                return ResourceManager.GetString("Rank.Auxiliary.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кандидат.
        /// </summary>
        public static string Rank_Candidate {
            get {
                return ResourceManager.GetString("Rank.Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⭡.
        /// </summary>
        public static string Rank_Candidate_Icon {
            get {
                return ResourceManager.GetString("Rank.Candidate.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дипломат.
        /// </summary>
        public static string Rank_Diplomat {
            get {
                return ResourceManager.GetString("Rank.Diplomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        public static string Rank_Employee {
            get {
                return ResourceManager.GetString("Rank.Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❮❮.
        /// </summary>
        public static string Rank_Employee_Icon {
            get {
                return ResourceManager.GetString("Rank.Employee.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Противник.
        /// </summary>
        public static string Rank_Enemy {
            get {
                return ResourceManager.GetString("Rank.Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый советник.
        /// </summary>
        public static string Rank_FirstAdvisor {
            get {
                return ResourceManager.GetString("Rank.FirstAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ▲.
        /// </summary>
        public static string Rank_FirstAdvisor_Icon {
            get {
                return ResourceManager.GetString("Rank.FirstAdvisor.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гость.
        /// </summary>
        public static string Rank_Guest {
            get {
                return ResourceManager.GetString("Rank.Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заступник.
        /// </summary>
        public static string Rank_Intercessor {
            get {
                return ResourceManager.GetString("Rank.Intercessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☆☆.
        /// </summary>
        public static string Rank_Intercessor_Icon {
            get {
                return ResourceManager.GetString("Rank.Intercessor.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Младший сотрудник.
        /// </summary>
        public static string Rank_JuniorEmployee {
            get {
                return ResourceManager.GetString("Rank.JuniorEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❮❮❮.
        /// </summary>
        public static string Rank_JuniorEmployee_Icon {
            get {
                return ResourceManager.GetString("Rank.JuniorEmployee.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Младший заступник.
        /// </summary>
        public static string Rank_JuniorIntercessor {
            get {
                return ResourceManager.GetString("Rank.JuniorIntercessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☆☆☆.
        /// </summary>
        public static string Rank_JuniorIntercessor_Icon {
            get {
                return ResourceManager.GetString("Rank.JuniorIntercessor.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Младший страж.
        /// </summary>
        public static string Rank_JuniorSentinel {
            get {
                return ResourceManager.GetString("Rank.JuniorSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ★★★.
        /// </summary>
        public static string Rank_JuniorSentinel_Icon {
            get {
                return ResourceManager.GetString("Rank.JuniorSentinel.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Младший специалист.
        /// </summary>
        public static string Rank_JuniorSpecialist {
            get {
                return ResourceManager.GetString("Rank.JuniorSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❙❙❙.
        /// </summary>
        public static string Rank_JuniorSpecialist_Icon {
            get {
                return ResourceManager.GetString("Rank.JuniorSpecialist.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неофит.
        /// </summary>
        public static string Rank_Neophyte {
            get {
                return ResourceManager.GetString("Rank.Neophyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⦁⦁⦁.
        /// </summary>
        public static string Rank_Neophyte_Icon {
            get {
                return ResourceManager.GetString("Rank.Neophyte.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изганнник.
        /// </summary>
        public static string Rank_Outcast {
            get {
                return ResourceManager.GetString("Rank.Outcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старший ауксилий.
        /// </summary>
        public static string Rank_SeniorAuxiliary {
            get {
                return ResourceManager.GetString("Rank.SeniorAuxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⭡⭡.
        /// </summary>
        public static string Rank_SeniorAuxiliary_Icon {
            get {
                return ResourceManager.GetString("Rank.SeniorAuxiliary.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старший сорудник.
        /// </summary>
        public static string Rank_SeniorEmployee {
            get {
                return ResourceManager.GetString("Rank.SeniorEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❮.
        /// </summary>
        public static string Rank_SeniorEmployee_Icon {
            get {
                return ResourceManager.GetString("Rank.SeniorEmployee.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старший заступник.
        /// </summary>
        public static string Rank_SeniorIntercessor {
            get {
                return ResourceManager.GetString("Rank.SeniorIntercessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☆.
        /// </summary>
        public static string Rank_SeniorIntercessor_Icon {
            get {
                return ResourceManager.GetString("Rank.SeniorIntercessor.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старший страж.
        /// </summary>
        public static string Rank_SeniorSentinel {
            get {
                return ResourceManager.GetString("Rank.SeniorSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ★.
        /// </summary>
        public static string Rank_SeniorSentinel_Icon {
            get {
                return ResourceManager.GetString("Rank.SeniorSentinel.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старший специалист.
        /// </summary>
        public static string Rank_SeniorSpecialist {
            get {
                return ResourceManager.GetString("Rank.SeniorSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❙.
        /// </summary>
        public static string Rank_SeniorSpecialist_Icon {
            get {
                return ResourceManager.GetString("Rank.SeniorSpecialist.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страж.
        /// </summary>
        public static string Rank_Sentinel {
            get {
                return ResourceManager.GetString("Rank.Sentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ★★.
        /// </summary>
        public static string Rank_Sentinel_Icon {
            get {
                return ResourceManager.GetString("Rank.Sentinel.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специалист.
        /// </summary>
        public static string Rank_Specialist {
            get {
                return ResourceManager.GetString("Rank.Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ❙❙.
        /// </summary>
        public static string Rank_Specialist_Icon {
            get {
                return ResourceManager.GetString("Rank.Specialist.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стажёр.
        /// </summary>
        public static string Rank_Trainee {
            get {
                return ResourceManager.GetString("Rank.Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⦁⦁.
        /// </summary>
        public static string Rank_Trainee_Icon {
            get {
                return ResourceManager.GetString("Rank.Trainee.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Капитан.
        /// </summary>
        public static string SquadMemberLevel_Captain {
            get {
                return ResourceManager.GetString("SquadMemberLevel.Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ◆.
        /// </summary>
        public static string SquadMemberLevel_Captain_Icon {
            get {
                return ResourceManager.GetString("SquadMemberLevel.Captain.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лейтенант.
        /// </summary>
        public static string SquadMemberLevel_Lieutenant {
            get {
                return ResourceManager.GetString("SquadMemberLevel.Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ◇.
        /// </summary>
        public static string SquadMemberLevel_Lieutenant_Icon {
            get {
                return ResourceManager.GetString("SquadMemberLevel.Lieutenant.Icon", resourceCulture);
            }
        }
    }
}
