//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace And9.Service.Award.Abstractions.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("And9.Service.Award.Abstractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бронза.
        /// </summary>
        public static string Award_Bronze {
            get {
                return ResourceManager.GetString("Award.Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медь.
        /// </summary>
        public static string Award_Copper {
            get {
                return ResourceManager.GetString("Award.Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Золото.
        /// </summary>
        public static string Award_Gold {
            get {
                return ResourceManager.GetString("Award.Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Герой.
        /// </summary>
        public static string Award_Hero {
            get {
                return ResourceManager.GetString("Award.Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Большой штраф.
        /// </summary>
        public static string Award_LargePenalty {
            get {
                return ResourceManager.GetString("Award.LargePenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний штраф.
        /// </summary>
        public static string Award_MediumPenalty {
            get {
                return ResourceManager.GetString("Award.MediumPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (нет).
        /// </summary>
        public static string Award_None {
            get {
                return ResourceManager.GetString("Award.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сапфир.
        /// </summary>
        public static string Award_Sapphire {
            get {
                return ResourceManager.GetString("Award.Sapphire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серебро.
        /// </summary>
        public static string Award_Silver {
            get {
                return ResourceManager.GetString("Award.Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Малый штраф.
        /// </summary>
        public static string Award_SmallPenalty {
            get {
                return ResourceManager.GetString("Award.SmallPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🟫.
        /// </summary>
        public static string AwardType_Bronze_Icon {
            get {
                return ResourceManager.GetString("AwardType.Bronze.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🟩.
        /// </summary>
        public static string AwardType_Copper_Icon {
            get {
                return ResourceManager.GetString("AwardType.Copper.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🟨.
        /// </summary>
        public static string AwardType_Gold_Icon {
            get {
                return ResourceManager.GetString("AwardType.Gold.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🟪.
        /// </summary>
        public static string AwardType_Hero_Icon {
            get {
                return ResourceManager.GetString("AwardType.Hero.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⤋.
        /// </summary>
        public static string AwardType_LargePenalty_Icon {
            get {
                return ResourceManager.GetString("AwardType.LargePenalty.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⇓.
        /// </summary>
        public static string AwardType_MediumPenalty_Icon {
            get {
                return ResourceManager.GetString("AwardType.MediumPenalty.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🟦.
        /// </summary>
        public static string AwardType_Sapphire_Icon {
            get {
                return ResourceManager.GetString("AwardType.Sapphire.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬜.
        /// </summary>
        public static string AwardType_Silver_Icon {
            get {
                return ResourceManager.GetString("AwardType.Silver.Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↓.
        /// </summary>
        public static string AwardType_SmallPenalty_Icon {
            get {
                return ResourceManager.GetString("AwardType.SmallPenalty.Icon", resourceCulture);
            }
        }
    }
}
